version: "2"
services:
  app:
    build:
      context: .
    env_file:
      - .env.phx
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:10.11
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bbb_lti_dev"
